---
title: "Control de calidad de clasificacion"
author: "Viacheslav Shalisko"
date: "12 de junio de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(maptools)
library(raster)
```

```{r}
verbose = 0

control_parcels_path <- "Control_zones.shp"

raster_path <- "../2016_classif/2016_clasificado.tif"

class_codes <- c(100,101,103,105,110,115,120,130,135,150,155,160,161,190,192,195,197,200)
class_legend <- c("Urbano",
                  "Urbano disperso",
                  "Infraestructura",
                  "SVA",
                  "Agr. riego",
                  "Agr. temporal",
                  "Pastizal",
                  "Matorral",
                  "BEsp",
                  "BTC",
                  "BTSC",
                  "BTemp disp.",
                  "BTemp dens.",
                  "Golf",
                  "AVU",
                  "VAS",
                  "BGal",
                  "Agua")
class_col <- c("gray20",
               "gray30",
               "gray40",
               "lightgray",
               "yellow",
               "lightyellow",
               "palegreen",
               "orange",
               "coral",
               "brown",
               "indianred3",
               "forestgreen",
               "darkgreen",
               "green",
               "seagreen3",
               "blue",
               "darkgreen",
               "navy")

```

## Visualización de datos 

```{r fig.height= 17, fig.width = 12}
control_parcels <- readShapePoly(control_parcels_path)

classification_raster <- raster(raster_path)
dim(classification_raster)

par(cex.axis = 0.8)
plot(classification_raster, axes = TRUE, legend = FALSE, 
     col = class_col, breaks = c(class_codes - 1,201), 
     main="Clasificación y parcelas de control")
plot(control_parcels, border = "red", add = TRUE)
legend("bottom", horiz = TRUE,
       legend = class_codes, fill = class_col, 
       bty = "n", cex = 0.8)
```

```{r}
## generar matriz de errores en blanco
var_num <- length(class_codes)
error_matrix <- matrix(rep(0,var_num * var_num), nrow = var_num, ncol = var_num)
rownames(error_matrix) <- class_codes
colnames(error_matrix) <- class_codes
```

## Muestreo del raster clasificado

```{r}
control_sampling <- extract(classification_raster, control_parcels)
```

## Generaión de matriz de confusión

```{r}

for (i in 1:length(control_sampling)) {
  primary_class <- control_parcels@data$Code_1[i]
  secondary_class <- control_parcels@data$Code_2[i]

  if (verbose) {
    cat("Parcela de control: ",as.character(control_parcels@data$GRID_ID[i]),"\n")
    cat("Clase primario = ",primary_class,"\n")
    cat("Clase secundario = ",secondary_class,"\n")
    cat("Pixeles observados = ",control_sampling[[i]],"\n")
    cat("Número de pixeles = ",length(control_sampling[[i]]),"\n\n")
  }  

  for (j in 1:length(control_sampling[[i]])) {
    if (control_sampling[[i]][j] == primary_class) {
      # coincidencia de clase primario
      ind_1 <- as.character(primary_class)
      error_matrix[ind_1,ind_1] <- error_matrix[ind_1,ind_1] + 1
    } else {
      if (control_sampling[[i]][j] == secondary_class) {
          # coincidencia de clase secundario
          ind_1 <- as.character(secondary_class)
          error_matrix[ind_1,ind_1] <- error_matrix[ind_1,ind_1] + 1
      } else {
          # valor primario esperado (de control) - filas del matriz
          ind_1A <- as.character(primary_class)
          # valor secundario esperado (de control) - filas del matriz          
          ind_1B <- as.character(secondary_class)          
          # valor observado (en clasificación) - columnas del matriz
          ind_2 <- as.character(control_sampling[[i]][j])
          error_matrix[ind_1A,ind_2] <- error_matrix[ind_1A,ind_2] + 0.5
          error_matrix[ind_1B,ind_2] <- error_matrix[ind_1B,ind_2] + 0.5
      }    
    }
  }
}

# representar matriz de confusión
cat("Matriz de confusión:\n")
round(error_matrix, digits = 0)

```

## Estimación del error de clasificación

```{r}
error_stat <- function(m, legend) {
  n <- sum(m)
  cat("Número de elementos: ",n,"\n")
  d <- diag(m)

  rowsums <- apply(m, 1, sum)
  colsums <- apply(m, 2, sum)
  p <- rowsums / n
  q <- colsums / n
  cat("\nSumas normalizadas en filas (p) y en columnas (q):","\n")
  print(data.frame(legend,p,q))

  # respuesta por clase
  recall <- d / colsums 
  # precición por clase
  precision <- d / rowsums 
  # Métrica F1 (media harmónica de precición y respuesta)
  f1 <- 2 * precision * recall / (precision + recall)
  cat("\nPrecición y respuesta por clase:","\n")
  print(data.frame(legend,precision, recall, f1))
  
  # precición general
  accuracy <- sum(d) / n
  cat("\nPrecición general: ",accuracy,"\n")  
  
  # métrica de precición kappa
  expaccuracy = sum(p * q)
  kappa = (accuracy - expaccuracy) / (1 - expaccuracy)
  cat("\nKappa de Cohen: ",kappa,"\n")
  
}

error_stat(error_matrix, class_legend)

```

## Estimación del Kappa de Cohen

```{r}
library(fmsb)
Kappa.test(error_matrix, conf.level=0.95) 

## obtener la estructura de la capa control_parcels
#str(control_parcels)
#as.character(control_parcels@data$GRID_ID)
#as.character(control_parcels@data$STDID1)
#as.character(control_parcels@data$STDID2)
#as.character(control_parcels@data$ANTRO)
```

