---
title: Flujo de proceso
---
flowchart LR
    L8@{ shape: docs, label: "Imagenes Landsat 8-9 2025"}
    S2@{ shape: docs, label: "Imagenes Sentinel 2 2025"}
    HR@{ shape: docs, label: "Datos de alta resolución Google Earth Engine (Airbus, SPOT)"}
    MDE@{ shape: doc, label: "MDE CEM v3 15 m"}
