journey
    title Succisión secundaria
    section Hábitat artificial y Disturbio
      Deforestación: 1: Disturbio
      Campo agrícola: 2: Disturbio
    section Hábitat inducido
      Pastizal inducido: 3: Herbáceo
      Matorral inducido: 4: Herbáceo, Arbustivo
      Vegetación secundaria arbórea: 4: Herbáceo, Arbustivo, Arbóreo
    section Hábitat natural
      Bosque primario abierto: 5:  Herbáceo, Arbustivo, Arbóreo
      Bosque primario denso: 5: Herbáceo, Arbóreo
