flowchart LR
  A1[Habitat]-->B1[Natural]
  A1-->B2[Inducido]
  A1-->B3[Artificial]
  A1-->B4[Acuatico]
  B1-->C7[Bosque templado abierto]
  B1-->C8[Bosque templado cerrado]
  B2-->C6[Bosque secundario]
  B2-->C2[Matorral]
  B2-->C1[Pastizal]
  B3-->C3[Agricultura]
  B3-->C4[Construido y sin vegetación]
  B4-->C5[Agua]
  C1-->D1[fa:fa-cow Pastizal inducido]
  C2-->D2[Matorral inducido]
  C6-->D3[Vegetación secundaria arborea]
  C3-->D4[fa:fa-seedling Plantaciones de arboles/Huertos]
  C3-->D5[fa:fa-wheat-awn Agricultura de temporal]
  C4-->D6[fa:fa-shop Construcciones]
  C4-->D7[Áreas sin vegetación aparente]
  C4-->D8[fa:fa-road Vialidades]
  C7-->D9[Bosque de encnio abierto]
  C8-->D10[Bosque de encnio cerrado]
  C7-->D11[Bosque de encnio-pino abierto]
  C8-->D12[Bosque de encnio-pino cerrado]
  C7-->D13[Bosque de pino-encnio abierto]
  C8-->D14[Bosque de pino-encino cerrado]
  C8-->D15[Bosque de galería]
  C5-->D16[Cuerpos de agua]
  style B1 fill:#1e882a99
  style B2 fill:#debc82
  style B3 fill:#a8b5b5
  style B4 fill:#797ff5
