flowchart LR
  A1[Habitat]-->B1[Natural]
  A1-->B2[Inducido]
  A1-->B3[Artificial]
  A1-->B4[Acuatico]
  B1-->C7[Bosque templado abierto]
  B1-->C8[Bosque templado cerrado]
  B2-->C6[Bosque secundario]
  B2-->C2[Matorral]
  B2-->C1[Pastizal]
  B3-->C3[Agricultura]
  B3-->C4[Construido y sin vegetación]
  B4-->C5[Agua]
  C1-->D1[Pastizal inducido]
  C2-->D2[Matorral inducido]
  C7-->D3[Bosque de encnio abierto]
  C8-->D4[Bosque de encnio cerrado]
  C7-->D5[Bosque de encnio-pino abierto]
  C8-->D6[Bosque de encnio-pino cerrado]
  C7-->D7[Bosque de pino-encnio abierto]
  C8-->D8[Bosque de pino-encino cerrado]
  C8-->D9[Bosque de galería]
