---
title: Flujo de proceso
---
flowchart LR
    L8@{ shape: docs, label: "Imagenes Landsat 8-9 Level 2 reflectancia superficie 2025 30 m"}
    S2@{ shape: docs, label: "Imagenes Sentinel 2 L2 reflectancia superficie 2025 10 m"}
    HR@{ shape: docs, label: "Datos de alta resolución Google Earth Engine (Airbus, SPOT) 1-5 m"}
    MDE@{ shape: doc, label: "MDE CEM v3 15 m"}
