journey
    title Succisión secundaria
    section Disturbio
      Deforestación: 1: Naturalidad
      Campo agrícola: 2: Naturalidad
      Abandono de campo acrícola: 2: Naturalidad
    section Hábitat inducido
      Pastizal inducido: 3: Naturalidad
      Matorral inducido: 4: Naturalidad
      Vegetación secundaria arbórea: 4: Naturalidad
    section Hábitat natural
      Bosque primario abierto: 5: Naturalidad
      Bosque primario denso: 5: Naturalidad
